---
- hosts: all
  become: yes
  gather_facts: false
 
  vars: 
    user: "ubuntu"
  
  tasks:
  
  - name: Update repository
    apt_repository:
      repo: 'ppa:git-core/ppa'
      state: present
  
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
  
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker
    remote_user: "{{ user }}"
    apt:
      name: docker-ce
      state: present
      update_cache: yes
  
  - name: Add remote "{{ user }}" user to "docker" group
    remote_user: "{{ user }}"
    user:
      name: "{{ user }}"
      group: "docker"
      append: yes
  
  - name: Install docker-compose
    remote_user: "{{ user }}"
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.3.1/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Clone a repo from git to directory
    ansible.builtin.git:
      repo: https://github.com/Shurenbergen/docker-testwork
      dest: /home/{{ user }}/docker-testwork
      clone: yes

  - name: Run docker-compose up
    command: docker-compose -f /home/{{ user }}/docker-testwork/docker-compose.yml up -d

    